name: Terraform CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: "EC2 Instance Name"
        required: true
        default: "my-server"
      instance_type:
        description: "Instance Type (t2.micro, t2.small, t2.medium)"
        required: true
        default: "t2.micro"
      username:
        description: "Username"
        required: true
        default: "rohit"
      key_name:
        description: "AWS Key Pair Name"
        required: true
        default: "rohit-test"
      action:
        description: "Terraform Action to run"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Get the code
        uses: actions/checkout@v3

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🔍 Terraform Init
        working-directory: terraform
        run: terraform init

      - name: ✅ Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: 📋 Terraform Plan
        working-directory: terraform
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          terraform plan \
            -var="instance_name=${{ github.event.inputs.instance_name }}" \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="key_name=${{ github.event.inputs.key_name }}" \
            -var="username=${{ github.event.inputs.username }}"

      - name: 🚀 Terraform Apply
        working-directory: terraform
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve \
            -var="instance_name=${{ github.event.inputs.instance_name }}" \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="key_name=${{ github.event.inputs.key_name }}" \
            -var="username=${{ github.event.inputs.username }}" \
            -var="ami=ami-07062e2a343acc423" \
            -var="region=us-east-2"

      - name: 💣 Terraform Destroy
        working-directory: terraform
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve \
            -var="instance_name=${{ github.event.inputs.instance_name }}" \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="key_name=${{ github.event.inputs.key_name }}" \
            -var="username=${{ github.event.inputs.username }}" \
            -var="ami=ami-07062e2a343acc423" \
            -var="region=us-east-2"