name: Terraform CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Get the code
        uses: actions/checkout@v3

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🔍 Terraform Init
        working-directory: terraform
        run: terraform init

      - name: ✅ Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: 📋 Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: 🚀 Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        #this is for testing